name = "WidgetsBase"
uuid = "eead4739-05f7-45a1-878c-cee36b57321c"
authors = ["Simon Danisch"]
version = "0.1.0"

[deps]
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
